version: '3.2'

services:
  app:
    restart: always
    build: .
    container_name: desafio_mb_labs
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres_mb_labs
    restart: always
    tty: true
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  migration:
    container_name: migrations
    build: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "postgres:5432",
        "--",
        "npm",
        "run",
        "migrate:docker"
      ]
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  db:
